apiVersion : apps/v1
kind : Deployment
metadata :
 name : my-web-deployment-replicas&Service 
 labels :
  app : my-application4k8s
  env : prod
  owner : Michael-V
spec :
 replicas : 3
 selector :
  matchLabels :
   project : cib
 template :
  metadata :
   labels :
    project : cib #pod-label-for-LB
  spec :
   containers :
   - name : httpd-cont
     image : httpd:latest
     ports :
     - containerPort: 80
---
apiVersion : v1
kind : Service
metadata : 
 name : pod-service
 labels :
  env : stage
  owner : Corp
spec :
 selector :
  project : cib  #pod-project-labels
 ports : 
 - name : httpd-listener
   protocol : TCP
   port : 8080 #LB port
   targetPort : 80 #pod pod
 type : ClusterIP 