apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
 template:
   
   metadata:
    name: myadpp-pod
    labels:
     app: myapp
     type: front-end
   spec:
     containers:
       - name: httpd-container
         image: httpd
 replicas: 3
 selector: 
  matchLabels:
    type: front-end
